#!/bin/bash

# This script configures the git submodule under magic-modules so that it is
# ready to create a new pull request.  It is cloned in a detached-head state,
# but its branch is relevant to the PR creation process, so we want to make
# sure that it's on a branch, and most importantly that that branch tracks
# a branch upstream.

set -e
set -x

shopt -s dotglob
cp -r magic-modules/* magic-modules-with-comment

pushd magic-modules-with-comment

# This says "check out the branch which contains HEAD, and set it up to track its upstream."
git checkout -t "$(git branch -a --contains "$(git rev-parse HEAD)" | grep -v "detached")"

pushd build/terraform

cat << EOF > ./downstream_body
$(git log -1 --pretty=%B)

<!-- This change is generated by MagicModules. -->
EOF
git checkout -t "$(git branch -a --contains "$(git rev-parse HEAD)" | grep -v "detached")"
cat << EOF > ./pr_comment 
I am a robot that works on MagicModules PRs!

I built this PR into one or more PRs on other repositories, and when those are closed, this PR will also be merged and closed.
depends: $(hub pull-request -b terraform-providers/terraform-provider-google:master -F ./downstream_body)
EOF
